spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    secret: test_secret