spring:
  profile.active: prod
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: root
    password: root123
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${SEC_SECRET}